[[constraint]]
  name = "github.com/alpancs/quranize"
  version = "1.4.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/alpancs/quranize-service"
